Add LogEventView as a member within LogParser
y-scope/log-surgeon pull request #11
Opened 2023-11-20 19:55 UTC by SharafMohamed

# References
Fix needed to remove static instantiation of LogEventView in https://github.com/y-scope/clp/pull/131

# Description
Added LogEventView as member of LogParser
Fixed bug in buffer-parser example

# Validation performed
Ran reader-parser and buffer-parser examples on test log

2023-11-22 15:26 UTC, SharafMohamed commented on src/log_surgeon/LogParser.hpp
>       * its tokens are stored into output_buffer.
commit 932bc49327a8a4a5dfe492135e836505e4c39dd5

2023-11-22 15:28 UTC, SharafMohamed commented on src/log_surgeon/LogParser.hpp
> +     * Reset the log event view to prepare for the next parse
commit 8e445a943d503cc33f6d6dd112b47f12b372463c

2023-11-22 21:41 UTC, SharafMohamed commented on src/log_surgeon/LogEvent.cpp
> +LogEventView::LogEventView() : m_log_parser{nullptr}, m_log_var_occurrences{0} {
moved to member declaration, change {0} to just {}
commit 19713b11d1fa86c3d0e15350cf9ad8e2f1266662

2023-11-22 21:42 UTC, SharafMohamed commented on src/log_surgeon/BufferParser.hpp
> +     * and only valid if ErrorCode::Success is returned.
commit 2ed0559ba9e7fc0354c5b6907f43932d70acd054

2023-11-22 21:44 UTC, SharafMohamed commented on examples/CMakeLists.txt
> +add_subdirectory(.. log-surgeon-build EXCLUDE_FROM_ALL)
This was changed so that the example files more closely follow actual use (e.g., instead of a relative path, we can use #include <log_surgeon/Constants.hpp>)

2023-11-22 21:47 UTC, SharafMohamed commented on examples/buffer-parser.cpp
> +    LogEventView const& event = parser.get_log_parser().get_log_event_view();
commit 32112d7e4a044cb9df09c3fd797d35b2cbad5dc0

2023-11-22 21:47 UTC, SharafMohamed commented on examples/reader-parser.cpp
> +    LogEventView const& event = parser.get_log_parser().get_log_event_view();
commit 32112d7e4a044cb9df09c3fd797d35b2cbad5dc0

2023-11-22 21:49 UTC, SharafMohamed commented on src/log_surgeon/LogParser.hpp
> +    auto generate_log_event_view_metadata() -> void;
Some applications don't need the metadata (e.g. CLP just compresses it directly without any additional analysis). Its pretty expensive to generate the metadata so its probably not ideal when additional analysis isn't needed.

2023-11-22 21:51 UTC, SharafMohamed commented on src/log_surgeon/LogParser.hpp
> +    auto generate_log_event_view_metadata() -> void;
One alternative might be a parse_and_generate_metadata() function that calls both?

2023-11-22 22:37 UTC, SharafMohamed commented on src/log_surgeon/LogParser.hpp
> +    auto generate_log_event_view_metadata() -> void;
Made a function to both parse and generate metadata. Made both metadata and parse functions private, although with more complicated metadata their might be an argument for calling parse() on its own (currently there isn't any noticeable performance change when always generating metadata even when not needed, e.g. CLP).
Commit 7b493e856221060dbe14d29c1ea1c4f64176e628

2023-11-22 23:28 UTC, SharafMohamed commented on examples/CMakeLists.txt
> +add_subdirectory(.. log-surgeon-build EXCLUDE_FROM_ALL)
Examples didn't compile after some previous PR.

2023-11-22 23:48 UTC, SharafMohamed commented on src/log_surgeon/LogEvent.hpp
> +    auto init(LogParser const* log_parser) -> void;
Changed to unique_ptr.
Commit 31c46b83ccded1d4fa640cd2540f4e6d42254341

2023-11-22 23:58 UTC, SharafMohamed commented on src/log_surgeon/ReaderParser.hpp
> +     * returned.
commit 932bc49327a8a4a5dfe492135e836505e4c39dd5

2023-11-23 00:06 UTC, kirkrodrigues commented on README.md
>  // Create a LogEventView (similar to a string_view)
I think this comment is kind of obsolete now

2023-11-23 01:24 UTC, kirkrodrigues requested changes

2023-11-23 01:24 UTC, kirkrodrigues commented on src/log_surgeon/LogParser.hpp
> +     * its tokens are stored into output_buffer.
```suggestion
     * its tokens are stored into m_log_event_view.
```

2023-11-23 13:22 UTC, SharafMohamed commented on README.md
>  // Create a LogEventView (similar to a string_view)
removed in commit e852580761b683c5599048aae7b3b357d75cd28a

2023-11-23 13:23 UTC, SharafMohamed commented on src/log_surgeon/ReaderParser.hpp
> +     * is only valid if ErrorCode::Success is returned.
commit 602c809653e6f044c6bf6566a2a1d66b75733f07

2023-11-23 13:25 UTC, SharafMohamed commented on src/log_surgeon/LogParser.hpp
> +     * its tokens are stored into output_buffer.
commit b87298c3f0756698db692ff2c510645e719225d2

2023-11-23 13:39 UTC, SharafMohamed commented on src/log_surgeon/LogEvent.hpp
> +    LogParser const* m_log_parser{nullptr};
Changed to a reference in commit 02acdc84eab20afe15f4d20fdb4adbf07b6460d3

2023-11-23 13:42 UTC, SharafMohamed commented on src/log_surgeon/LogEvent.cpp
> +            logtype += ">";
commit cd45f29e55196e8c104c678e336a58515f690078

2023-11-23 18:45 UTC, kirkrodrigues approved these changes

2023-11-23 20:50 UTC, merged