Add DFA intersection
y-scope/log-surgeon pull request #17
Opened 2024-02-02 21:10 UTC by SharafMohamed

# Description
- Add a method to DFA that returns its intersect with another DFA. This returns each schema type in the DFA that have at least 1 string in its language that can match the DFA passed in to the method.
- Add test for DFA intersect

# Validation performed
- Ran buffer-parser, reader-parser, and intersect test with expected output

2024-02-16 12:28 UTC, kirkrodrigues requested changes

2024-02-16 12:28 UTC, kirkrodrigues commented on src/log_surgeon/finite_automata/RegexDFA.hpp
> +    auto is_accepting() const -> bool;
```suggestion
    [[nodiscard]] auto is_accepting() const -> bool;
```

2024-02-16 12:28 UTC, kirkrodrigues commented on src/log_surgeon/finite_automata/RegexDFA.hpp
> +    auto get_intersect(std::unique_ptr<RegexDFA> const& dfa_in) -> std::set<uint32_t>;
* Add docstring
* Can be made const and can add `[[nodiscard]]`

2024-02-16 12:28 UTC, kirkrodrigues commented on src/log_surgeon/finite_automata/RegexDFA.hpp
> +    auto generate_reachable_pairs() -> std::set<RegexDFAStatePair>;
```suggestion
    auto get_reachable_pairs() -> std::set<RegexDFAStatePair>;
```
Or do you feel like that's misleading?

2024-02-16 12:28 UTC, kirkrodrigues commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +    // TODO: currently assumes it is a byte input, needs to handle utf8 as well
```suggestion
    // TODO: Handle UTF-8 (multi-byte transitions) as well
```

2024-02-16 12:28 UTC, kirkrodrigues commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +            reachable_pairs.emplace(m_state1->next(i), m_state2->next(i));
`next` can be a non-trivial method call (for UTF-8), so let's extract it into a variable for use in both the condition and emplace.

2024-02-16 12:28 UTC, kirkrodrigues commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +    return m_state1->is_accepting() && m_state2->is_accepting();
This seems trivial enough to go directly in the header?

2024-02-16 12:28 UTC, kirkrodrigues commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +    return m_state1->get_tags();
Seems trivial enough for the header?

2024-02-16 12:28 UTC, kirkrodrigues commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +    // TODO: currently assumes it is a byte input, needs to handle utf8 as well
Do we need to repeat this TODO here?

2024-02-16 12:28 UTC, kirkrodrigues commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +        unused_pairs.erase(unused_pairs.begin());
Let's cache `unused_pairs.begin()` in a variable above and then use it here.

2024-02-16 12:28 UTC, kirkrodrigues commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +            std::vector<int> const& tags = current_pair.get_first_tags();
```suggestion
            auto tags = current_pair.get_first_tags();
```

2024-02-16 12:28 UTC, kirkrodrigues commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +    std::set<RegexDFAStatePair<DFAStateType>> unused_pairs;
How about `new_pairs`?

2024-02-16 12:28 UTC, kirkrodrigues commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +    std::set<RegexDFAStatePair<DFAStateType>> used_pairs;
How about `visited_pairs`?

2024-02-16 12:28 UTC, kirkrodrigues commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +        }
* To be more efficient, we could pass in the `unused_pairs` set and have `generate_reachable_pairs` insert directly into it, right?
* We don't need to check for existence before insertion since it's a set, right?

2024-02-16 12:28 UTC, kirkrodrigues commented on examples/intersect-test.cpp
As we discussed offline:
* Let's try to get rid of the use of a lexer in this file to simplify the code
* Let's try to move this into a new unit-test executable.

2024-02-21 16:05 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.hpp
> +    bool operator<(RegexDFAStatePair const& rhs) const {
Changed in commit 1 - 657d58db6453a3fe1f9e790bae710c3818989c64

2024-02-21 16:05 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.hpp
> +     * @return if both pairs are accepting
Changed in commit 1 - 657d58db6453a3fe1f9e790bae710c3818989c64

2024-02-21 16:05 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.hpp
> +    auto is_accepting() const -> bool;
Changed in commit 1 - 657d58db6453a3fe1f9e790bae710c3818989c64

2024-02-21 16:07 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +    // TODO: currently assumes it is a byte input, needs to handle utf8 as well
Changed in commit 1 - 657d58db6453a3fe1f9e790bae710c3818989c64

2024-02-21 16:08 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +            std::vector<int> const& tags = current_pair.get_first_tags();
Changed in commit 1 - 657d58db6453a3fe1f9e790bae710c3818989c64

2024-02-21 16:10 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +    // TODO: currently assumes it is a byte input, needs to handle utf8 as well
I think this is needed as its 2 separate functions that need to be changed, alternatively we just put it in the header or something, but then when UTF-8 is implemented we're going to have to find these 2 places again.

Changed wording in commit 2 - 657d58db6453a3fe1f9e790bae710c3818989c64

2024-02-21 16:16 UTC, SharafMohamed commented on examples/intersect-test.cpp
Removed lexer from the file in commit 1: 24040741f8f89c1bb80b4775f760e7dc0f36ea54 and 52b51b1c947445f9fa50af742c21c4a52adb238f 

***Still need to move into new unit-test executable.

2024-02-21 16:24 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +    return m_state1->is_accepting() && m_state2->is_accepting();
Moved in commit 3: 5d78615192b2ce1c79fad3388b0f480941106445

2024-02-21 16:24 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +    return m_state1->get_tags();
Moved in commit 3: 5d78615192b2ce1c79fad3388b0f480941106445

2024-02-21 16:45 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.hpp
> +        return m_state1 < rhs.m_state1;  // assume that you compare the record based on a
Whoops, a was a field in the example code I used, forgot to remove the comment. 
Removed in commit 4: a598899484de6c6a039368792a297241376f4690

2024-02-21 17:32 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +    std::set<RegexDFAStatePair<DFAStateType>> unused_pairs;
Rename in commit 5: 5eed3d33aa7e8827f20bfed5bdf133f2f86bea48

2024-02-21 17:33 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +    std::set<RegexDFAStatePair<DFAStateType>> used_pairs;
Rename in commit 5: 5eed3d33aa7e8827f20bfed5bdf133f2f86bea48

2024-02-22 14:46 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.hpp
> +    /// TODO: a lot of this pointer usage could probably be references
Doesn't make sense to use references when the stored elements are originally unique_ptrs.
Removed TODO in commit 6: 6564fb12221620ed79ce4197ed5686b2d449b47f

2024-02-22 15:29 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.hpp
> +    bool operator<(RegexDFAStatePair const& rhs) const {
Added docstring in commit 7: 496d53afc5c9701dc6277e0f0d81d24b133face2

2024-02-22 16:20 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.hpp
> +    auto get_intersect(std::unique_ptr<RegexDFA> const& dfa_in) -> std::set<uint32_t>;
Updated in commit 8: d25beb655486b6def76671fbb5c38d89ccaf81ff

2024-02-22 16:24 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +            reachable_pairs.emplace(m_state1->next(i), m_state2->next(i));
Optimized in commit 9: b850178ed04b5217ec7b61473f162271b2aedd27

2024-02-22 16:39 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +        unused_pairs.erase(unused_pairs.begin());
Modified how its used in commit 10: 00f14b7730831977ad4bea0747b95db0146aa912

2024-02-22 17:36 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +        unused_pairs.erase(unused_pairs.begin());
Changed name from _itt to _it in commit 11 : de43c33e76b1eee7306077e7e8031e3ca601b7fe

2024-02-22 17:53 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +        }
Optimized in commit 12: 758cc7cbe7a1ebf8d4064882ef9786855f7d240d

2024-02-22 17:55 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +        }
FIxed errent return in commit 13: 8ca54a7e34980b955160391efded6e034ac8e27e

2024-02-23 20:27 UTC, kirkrodrigues requested changes
Minor comments.

2024-02-23 20:27 UTC, kirkrodrigues commented on examples/intersect-test.cpp
Don't forget to format with clang-format.

2024-02-23 20:27 UTC, kirkrodrigues commented on examples/intersect-test.cpp
> +    std::unique_ptr<log_surgeon::SchemaAST> schema_ast = schema.release_schema_ast_ptr();
```suggestion
    auto schema_ast = schema.release_schema_ast_ptr();
```

2024-02-23 20:27 UTC, kirkrodrigues commented on examples/intersect-test.cpp
> +    std::unique_ptr<RegexDFA<RegexDFAByteState>> dfa2 = ByteLexer::nfa_to_dfa(nfa);
```suggestion
    auto dfa2 = ByteLexer::nfa_to_dfa(nfa);
```

2024-02-23 20:27 UTC, kirkrodrigues commented on examples/intersect-test.cpp
> +    std::set<uint32_t> schema_types = dfa1->get_intersect(dfa2);
```suggestion
    auto schema_types = dfa1->get_intersect(dfa2);
```

2024-02-23 20:27 UTC, kirkrodrigues commented on src/log_surgeon/BufferParser.hpp
>       * Constructs the parser using the given schema object.
```suggestion
     * Constructs the parser using the given schema AST.
```

2024-02-23 20:27 UTC, kirkrodrigues commented on src/log_surgeon/ReaderParser.hpp
>       * Constructs the parser using the given schema object.
```suggestion
     * Constructs the parser using the given schema AST.
```

2024-02-23 20:27 UTC, kirkrodrigues commented on src/log_surgeon/finite_automata/RegexDFA.hpp
> +     * true if m_state2 in lhs has a lower address than in rhs, false otherwise
```suggestion
     * @return Whether m_state1 in lhs has a lower address than in rhs, or they're equal and
     * m_state2 in lhs has a lower address than in rhs
```

2024-02-23 20:27 UTC, kirkrodrigues commented on src/log_surgeon/finite_automata/RegexDFA.hpp
> +     * store any reachable pair not previously visited in unvisited_pairs
```suggestion
     * Generates all pairs reachable from the current pair via any string and stores any reachable
     * pair not previously visited in unvisited_pairs
     * @param visited_pairs Previously visited pairs
     * @param unvisited_pairs Set to add unvisited reachable pairs to
```

2024-02-23 20:27 UTC, kirkrodrigues commented on src/log_surgeon/finite_automata/RegexDFA.hpp
> +     * @return set of schema types reachable by dfa_in
```suggestion
     * @return The set of schema types reachable by dfa_in
```

2024-02-23 20:27 UTC, kirkrodrigues commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +    std::set<RegexDFAStatePair> reachable_pairs;
```suggestion
```

2024-02-23 20:27 UTC, kirkrodrigues commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +            RegexDFAStatePair<DFAState> reachable_pair(next_state1, next_state2);
```suggestion
            RegexDFAStatePair<DFAState> reachable_pair{next_state1, next_state2};
```

2024-02-24 00:29 UTC, kirkrodrigues approved these changes

2024-02-24 01:26 UTC, merged