Update clang-format and format code
y-scope/log-surgeon pull request #18
Opened 2024-07-17 14:46 UTC by SharafMohamed

# Description
Update clang-format and format code.

# Validation performed
Ran reader-parser and buffer-parser with expected output.

2024-07-18 18:52 UTC, kirkrodrigues requested changes

2024-07-18 18:52 UTC, kirkrodrigues commented on .clang-format
> +|mongocxx|msgpack|simdjson|spdlog|sqlite3|string_utils|yaml-cpp|zstd)"
We only need Catch2 since we don't use any other libraries in this project, right?

2024-07-18 18:52 UTC, kirkrodrigues commented on .clang-format
> +  - Regex: "^\".+\""
The way this project is written, the project headers are all included using non-relative includes, so we need to configure clang-format in the same way. We also need to move it to be the first regex otherwise the system header regexes will match `<log_surgeon` first.

2024-07-18 18:52 UTC, kirkrodrigues commented on .clang-format
Let's also run clang-format on `examples`.

2024-07-19 14:52 UTC, SharafMohamed commented on .clang-format
Done

2024-07-19 14:52 UTC, SharafMohamed commented on .clang-format
> +|mongocxx|msgpack|simdjson|spdlog|sqlite3|string_utils|yaml-cpp|zstd)"
Changed

2024-07-19 14:52 UTC, SharafMohamed commented on .clang-format
> +  - Regex: "^\".+\""
Changed

2024-07-19 16:52 UTC, kirkrodrigues approved these changes
For the PR title, how about:

Update clang-format config and reformat code.

2024-07-26 02:25 UTC, merged