Update workflow to perform linting.
y-scope/log-surgeon pull request #19
Opened 2024-07-26 02:29 UTC by SharafMohamed

# Description
Update workflow to perform linting.

# Validation performed
Changed yml and cpp files to confirm workflow correctly reports errors. Fixed errors to determine workflow runs successfully.

2024-07-30 15:10 UTC, kirkrodrigues requested changes

2024-07-30 15:10 UTC, kirkrodrigues commented on lint-requirements.txt
> +yamllint>=1.35.1
```suggestion
clang-format>=18.1.5
yamllint>=1.35.1
```

We don't need `black` nor `ruff` since we don't have any Python code in this repo.

2024-07-30 15:10 UTC, kirkrodrigues commented on lint-tasks.yml
> +      - "examples/**/*.tpp"
Alphabetize

2024-07-30 15:10 UTC, kirkrodrigues commented on lint-tasks.yml
> +          Taskfile.yml
```suggestion
        yamllint \
          --config-file "{{.ROOT_DIR}}/tools/yscope-dev-utils/lint-configs/.yamllint.yml" \
          --strict \
          .github \
          .yamllint.yml \
          .clang-format \
          .clang-tidy \
          lint-tasks.yml \
          Taskfile.yml
```

* Added the line to use the `yscope-dev-utils` config file.
* Added `.clang-tidy` to the list of linted files (you'll need to update it to pass the linter).

2024-07-30 15:10 UTC, kirkrodrigues commented on Taskfile.yml
> +  G_BUILD_DIR: "{{.ROOT_DIR}}/target"
Should be `build` rather than `target`, right?

2024-07-30 15:10 UTC, kirkrodrigues commented on Taskfile.yml
> +  G_LINT_VENV_DIR: "{{.G_BUILD_DIR}}/lint-venv"
This is already in `lint-tasks.yml` so we can drop it from here (global variables in included Taskfiles become global in this Taskfile).

2024-07-30 15:10 UTC, kirkrodrigues commented on Taskfile.yml
> +    deps: ["lint"]
I think it's more typical for the default task to be to build the project, so I would rather drop this task for now.

2024-07-30 15:10 UTC, kirkrodrigues commented on Taskfile.yml
> +    cmds: ["rm -rf '{{.G_BUILD_DIR}}' '{{.G_LINT_VENV_DIR}}'"]
```suggestion
  clean: "rm -rf '{{.G_BUILD_DIR}}'"
```

* Since `G_LINT_VENV_DIR` is inside `G_BUILD_DIR`, we can just rely on deleting the build directory.
* We can use a shorthand since the task is just one command.

2024-07-30 15:10 UTC, kirkrodrigues commented on Taskfile.yml
> +          OUTPUT_FILE: "{{.CHECKSUM_FILE}}"
All of this is covered by `lint-tasks.yml` so we can drop it, right?

2024-08-02 12:57 UTC, SharafMohamed commented on .github/workflows/build.yaml
> +    runs-on: "${{ matrix.os }}"
Linter complains if there is no space.

2024-08-02 13:12 UTC, kirkrodrigues requested changes
A few more minor things

2024-08-02 13:12 UTC, kirkrodrigues commented on lint-tasks.yml
> +  G_BUILD_DIR: "{{.ROOT_DIR}}/build"
I would put `G_BUILD_DIR` in the main task file since that's where it's first used (by `init`).

2024-08-02 13:12 UTC, kirkrodrigues commented on .github/workflows/build.yaml
> +      - run: "cmake -B ./build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}"
```suggestion
      - run: "cmake -B ./build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}"
```

2024-08-02 13:12 UTC, kirkrodrigues commented on .github/workflows/build.yaml
> +      - run: "cmake --build ./build --config ${{ matrix.build_type }}"
```suggestion
      - run: "cmake --build ./build --config ${{matrix.build_type}}"
```

2024-08-02 13:12 UTC, kirkrodrigues commented on .github/workflows/build.yaml
> +      - run: "cmake -S examples -B ./examples/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}"
```suggestion
      - run: "cmake -S examples -B ./examples/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}"
```

2024-08-02 13:12 UTC, kirkrodrigues commented on .github/workflows/build.yaml
> +      - run: "cmake --build ./examples/build --config ${{ matrix.build_type }}"
```suggestion
      - run: "cmake --build ./examples/build --config ${{matrix.build_type}}"
```

2024-08-02 16:26 UTC, kirkrodrigues approved these changes
For the PR title & commit body, how about:

Add linting tools:
* Add linting for YAML and C++ files and fix violations.
* Add Taskfile tasks to run linters.
* Add GitHub workflow to run linters periodically and on commit.

2024-08-02 17:50 UTC, merged