Add capture groups to schema AST.
y-scope/log-surgeon pull request #20
Opened 2024-07-26 13:07 UTC by SharafMohamed

# Description
- Initial step for implementing parsing with capture groups.  
- Currently only adds capture group to AST, but doesn't add to NFA/DFA.
- Move initialization of regex_special_characters into cpp to make it more clear what the lexical rules are for the schema parser.

# Validation performed
- Examples work.

2024-07-31 22:38 UTC, LinZhihao-723 requested changes
For the validation, iiuc the `capture` rule isn't parsed yet right? Do we have more detailed explanation about the validation steps?

2024-07-31 22:38 UTC, LinZhihao-723 commented on src/log_surgeon/finite_automata/RegexAST.hpp
> +    std::string m_name;
How about `m_group_name` since it's the name of the captured group?

2024-07-31 22:38 UTC, LinZhihao-723 commented on src/log_surgeon/finite_automata/RegexAST.hpp
> +class RegexASTCapture : public RegexAST<NFAStateType> {
Do we need a method to get the underlying name?

2024-07-31 22:38 UTC, LinZhihao-723 commented on src/log_surgeon/finite_automata/RegexAST.hpp
> +            std::unique_ptr<RegexAST<NFAStateType>> /*regex*/
How about moving the implementation from tpp to here?
Even if we don't, we should complete the signature with `name` and `regex` explicitly named instead of using comments

2024-07-31 22:38 UTC, LinZhihao-723 commented on src/log_surgeon/finite_automata/RegexAST.tpp
> +        : m_name(name),
```suggestion
        : m_name(std::move(name)),
```

2024-07-31 22:38 UTC, LinZhihao-723 commented on src/log_surgeon/finite_automata/RegexAST.hpp
> +     * lexer rule containing RegexASTCat at a leaf node in its AST
```suggestion
     * Sets `is_possible_input` to specify which utf8 characters are allowed in a
     * lexer rule containing `RegexASTCat` at a leaf node in its AST
```

2024-07-31 22:38 UTC, LinZhihao-723 commented on src/log_surgeon/finite_automata/RegexAST.hpp
> +     * RegexASTCapture before transitioning to a pre-tagged end_state
```suggestion
     * Adds the needed `RegexNFA::states` to the passed in nfa to handle a
     * `RegexASTCapture` before transitioning to a pre-tagged `end_state`
```

2024-07-31 22:38 UTC, LinZhihao-723 commented on src/log_surgeon/finite_automata/RegexAST.hpp
> +    std::unique_ptr<RegexAST<NFAStateType>> m_regex;
`m_regex` is a bit confusing, since the class is also called `RegexXXX`. Maybe `m_pattern` or sth indicating that it's a sub AST of the pattern to capture?

2024-07-31 22:38 UTC, LinZhihao-723 commented on src/log_surgeon/LogParser.cpp
> +        if (rule->m_name == "capture") {
```suggestion
        if ("capture" == rule->m_name) {
```

2024-08-02 15:22 UTC, SharafMohamed commented
> For the validation, iiuc the `capture` rule isn't parsed yet right? Do we have more detailed explanation about the validation steps?

For validation, we updated the schema.txt in the examples to cancel newly added special characters and added a capture group variable. The capture group variable is only used to create the schema AST, and is currently ignored during log parsing. So the current validation only shows that the capture group change (inclusion of capture groups in the schema.txt and schema AST) doesn't break any existing functionality. 

Currently LogSurgeon has no unit-tests, so there is actually no guarantee any of the schema AST stuff was previously correct, all we know is that the end-to-end benchmarks are succeeding. The next PR is going to address the unit test issue. So maybe we wait on that PR, and add some unit tests for testing the schema AST. Other than that, the only other way to test it would be after the next few PRs that adds tags to the DFA and then the log parsing change, which isn't the best option.

2024-08-02 18:10 UTC, SharafMohamed commented on src/log_surgeon/SchemaParser.hpp
> +    static std::unordered_map<char, std::string> m_special_regex_characters;
Added inline back.

2024-08-02 18:10 UTC, SharafMohamed commented on src/log_surgeon/SchemaParser.cpp
> +
Removed.

2024-08-02 18:12 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexAST.hpp
> +    RegexASTCapture(RegexASTCapture const& rhs)
Whoops, definitely need to `m_name` as well.

2024-08-02 18:15 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexAST.hpp
> +    std::string m_name;
Changed.

2024-08-02 18:18 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexAST.hpp
> +            std::unique_ptr<RegexAST<NFAStateType>> /*regex*/
All the classes inheriting from RegexAST currently define their constructors in the tpp. For now going to leave it in the tpp for consistency, even though I agree it should be in the header. Will do a following PR to focus on fixing some stylistic issues that applies to more than just the code touched here. 

Changed signature to be explicit.

2024-08-02 18:23 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexAST.hpp
> +     * lexer rule containing RegexASTCat at a leaf node in its AST
Updated.

2024-08-02 18:25 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexAST.hpp
> +     * RegexASTCapture before transitioning to a pre-tagged end_state
Changed and applied same idea to other comments in RegexASTCapture class.

2024-08-02 18:28 UTC, SharafMohamed commented on src/log_surgeon/LogParser.cpp
> +        if (rule->m_name == "capture") {
Swapped.

2024-08-02 18:34 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexAST.hpp
> +    std::unique_ptr<RegexAST<NFAStateType>> m_regex;
Its not a subAST, its the entire AST for the capture group. What about m_group_regex_ast, as it is a RegexAST?

2024-08-02 18:44 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexAST.hpp
> +class RegexASTCapture : public RegexAST<NFAStateType> {
I don't think so. What we need to make this class useful is for the add function to do more than just connect the NFA to the end_state, which is essentially a null operation. This requires the tagged DFA PR, so for now not much can be done.

2024-08-03 00:19 UTC, LinZhihao-723 commented on src/log_surgeon/finite_automata/RegexAST.hpp
> +    std::unique_ptr<RegexAST<NFAStateType>> m_regex;
yeah make sense. `m_group_regex_ast` sounds better

2024-08-03 00:35 UTC, LinZhihao-723 commented
> > For the validation, iiuc the `capture` rule isn't parsed yet right? Do we have more detailed explanation about the validation steps?
> 
> For validation, we updated the schema.txt in the examples to cancel newly added special characters and added a capture group variable. The capture group variable is only used to create the schema AST, and is currently ignored during log parsing. So the current validation only shows that the capture group change (inclusion of capture groups in the schema.txt and schema AST) doesn't break any existing functionality.
> 
> Currently LogSurgeon has no unit-tests, so there is actually no guarantee any of the schema AST stuff was previously correct, all we know is that the end-to-end benchmarks are succeeding. The next PR is going to address the unit test issue. So maybe we wait on that PR, and add some unit tests for testing the schema AST. Other than that, the only other way to test it would be after the next few PRs that adds tags to the DFA and then the log parsing change, which isn't the best option.

I see. For the validation performed, I was confused by the description since my understanding is the same as your reply. I think the validation description can be sth like "Ensure the newly added AST doesn't break the existing demo in examples."

2024-08-03 20:10 UTC, LinZhihao-723 requested changes
Final nit fix and then I will approve

2024-08-03 20:10 UTC, LinZhihao-723 commented on src/log_surgeon/SchemaParser.cpp
> +
```suggestion
```

2024-08-06 21:29 UTC, SharafMohamed commented on src/log_surgeon/SchemaParser.cpp
> +
I'm going to PR the unit test framework separately, and then add a few unit tests to this PR before we approve it.

2024-08-06 21:30 UTC, SharafMohamed commented
I'm going to PR the unit test framework separately, and then add a few unit tests to this PR before we approve it.

2024-08-07 00:57 UTC, LinZhihao-723 commented
> I'm going to PR the unit test framework separately, and then add a few unit tests to this PR so you can review them with this.

I will approve now and pass it to @kirkrodrigues

2024-08-07 00:57 UTC, LinZhihao-723 approved these changes

2024-08-15 04:55 UTC, LinZhihao-723 approved these changes
The unit test makes sense to me

2024-08-15 04:55 UTC, LinZhihao-723 commented on tests/test-lexer.cpp
> +        schema.add_variable("capture", "u(?<uID>[0-9]+)", -1);
Nit: we can make `"capture"` as a `constexpr std::string_view`

2024-08-15 06:31 UTC, SharafMohamed commented on tests/test-lexer.cpp
> +        schema.add_variable("capture", "u(?<uID>[0-9]+)", -1);
What about const std::string so it can be used with add_variable(), unless you think add_variable() should be modified.

2024-08-16 11:39 UTC, merged