Add unit test framework
y-scope/log-surgeon pull request #21
Opened 2024-08-07 01:15 UTC by SharafMohamed

# Description
- Add unit test framework.
- Add a unit test for creating a schema object.
- Add unit tests to linter.

# Validation performed
- Unit test compiles and runs successfully.

2024-08-08 11:28 UTC, kirkrodrigues requested changes

2024-08-08 11:28 UTC, kirkrodrigues commented on tests/CMakeLists.txt
One day we'll have an automated formatter for CMake files, but for now let's format things semi-manually to match our C++ format style:

* If the tokens inside parentheses span multiple lines...
  * ... let's put the first token on the line after the opening parenthesis.
  * ... let's double-indent the tokens on each line (if you're using CLion, the built-in formatter should do this for you)
* If the tokens inside parentheses can fit on one line, let's leave them on one line unless it hurts clarity.

2024-08-08 11:28 UTC, kirkrodrigues commented on tests/CMakeLists.txt
> +add_executable(unitTest ${SOURCE_FILES_unitTest})
Let's call the unit test exe `unit-test` rather than `unitTest` to follow our latest executable naming conventions. `unitTest` is a legacy from when we first started the clp project.

2024-08-08 11:28 UTC, kirkrodrigues commented on tests/CMakeLists.txt
> +                           ${CMAKE_SOURCE_DIR}/src
Nit: Alphabetize

2024-08-08 11:28 UTC, kirkrodrigues commented on tests/CMakeLists.txt
> +)
Let's break this into two variables:

* One for `SOURCES_LOG_SURGEON`
* One for `SOURCES_TESTS`

2024-08-08 11:28 UTC, kirkrodrigues commented on CMakeLists.txt
> +include(tests/CMakeLists.txt)
```suggestion
add_subdirectory(tests)
```

`add_subdirectory` is the more CMake-way to add a target. It does have some caveats though:

* You'll need to make the source paths in `tests/CMakeLists.txt` relative to the actual folder structure.
* You'll need to add this to the end of `tests/CMakeLists.txt`:
  ```cmake
  set_target_properties(
        unit-test
        PROPERTIES
        RUNTIME_OUTPUT_DIRECTORY
        "${PROJECT_BINARY_DIR}"
  )
  ```
  * Although, if you follow the Catch2 v2->v3 migration guide, we can switch to running tests using `ctest` from inside the build directory.

2024-08-08 11:33 UTC, kirkrodrigues commented on tests/test-lexer.cpp
> +#include <unistd.h>
Forgot this in the previous review: Why do we need this header?

2024-08-13 11:16 UTC, SharafMohamed commented on tests/test-lexer.cpp
> +#include <unistd.h>
We don't, removed.

2024-08-14 09:50 UTC, kirkrodrigues requested changes

2024-08-14 09:50 UTC, kirkrodrigues commented on tests/CMakeLists.txt
> +find_package(Catch2 3 REQUIRED)
* Let's move this into the main CMakeLists.txt (perhaps just after the project command) so that it's easier to all track dependencies from one place.
* Let's also move the `include` statements below into the main CMakeLists.txt, just after the `find_package` command. We should also add if guards around them following the guide [here](https://cliutils.gitlab.io/modern-cmake/chapters/testing.html).

2024-08-14 09:50 UTC, kirkrodrigues commented on tests/CMakeLists.txt
> +set(SOURCES_LOG_SURGEON
```suggestion
set(
        SOURCES_LOG_SURGEON
```

2024-08-14 09:50 UTC, kirkrodrigues commented on CMakeLists.txt
> +add_subdirectory(tests)
Let's add if guards around this following the guide [here](https://cliutils.gitlab.io/modern-cmake/chapters/testing.html).

2024-08-14 09:50 UTC, kirkrodrigues commented on .github/workflows/build.yaml
> +          submodules: "recursive"
We can drop this since we're no longer using submodules.

2024-08-14 09:50 UTC, kirkrodrigues commented on .github/workflows/build.yaml
> +        run: "./install-catch2.sh 3.6.0"
```suggestion
        run: |-
          apt-get update
          apt-get install -y catch2
```

Since the GH `ubuntu-latest` runner is new enough, we may as well use the apt package and save some time running this workflow.

2024-08-14 09:50 UTC, kirkrodrigues commented on .github/workflows/build.yaml
> +        run: "./build/tests/unit-test"
```suggestion
        run: "cmake --build ./build --target test"
```

This should work after making the suggested cmake changes.

2024-08-14 09:50 UTC, kirkrodrigues commented on .github/workflows/build.yaml
> +        run: |
```suggestion
        run: |-
```

This is minor, but I prefer to reduce the extraneous newlines.

2024-08-14 11:03 UTC, SharafMohamed commented on .github/workflows/build.yaml
> +        run: "./build/tests/unit-test"
Used ctest instead

2024-08-14 11:14 UTC, kirkrodrigues approved these changes
For the PR title, how about:

Add unit testing framework.

2024-08-14 11:17 UTC, merged