Fix clang-tidy errors in RegexAST.hpp
y-scope/log-surgeon pull request #23
Opened 2024-08-17 12:48 UTC by SharafMohamed

# References
- Add GSL for gsl::at and gsl::owner
- Use [maybe unused]
- Use std::array in place of c-array
- Follow rule of 5
- Did not move RegexAST.tpp into RegexAST.hpp yet to reduce the size of the PR. In following PR will fix RegexAST.tpp, then another PR to combine them.

2024-08-27 18:29 UTC, kirkrodrigues requested changes

2024-08-27 18:29 UTC, kirkrodrigues commented on CMakeLists.txt
> +    GSL
Let's continue discussing this offline.

2024-08-28 08:42 UTC, kirkrodrigues commented on CMakeLists.txt
> +    ${GSL_SOURCE_DIR}/include
Fixed.

2024-08-28 11:39 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexAST.hpp
> +    auto operator=(RegexAST&& rhs) noexcept -> RegexAST& = default;
Used protected instead

2024-08-28 11:49 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexAST.hpp
> +            for (auto const& [fst, snd] : m_ranges) {
Begin + end is fine, this was just CLion auto-formatting it to fst and snd.

2024-08-28 12:04 UTC, kirkrodrigues approved these changes

2024-08-28 12:05 UTC, kirkrodrigues commented
For the PR title, how about:

Fix clang-tidy errors in RegexAST.hpp; Add Microsoft GSL as a dependency.

2024-08-28 12:26 UTC, merged