Naming cleanup for regex rules, NFA, and DFA.
y-scope/log-surgeon pull request #36
Opened 2024-09-12 12:58 UTC by SharafMohamed

# Description
- Move `Rule` struct into its own class called `LexicalRule`.
- As rule stores an integer, refer to member as `variable_id` instead of `name`.
- As the name tag is going to be used for tagged-NFAs, refer to NFA/DFA matches as `matching_variable_id` instead of `tag`.
- Use full names for vars (e.g., `r` renamed to `rule`).
- Clarify which states are NFA states and which are DFA states.

# Validation performed
- Examples and unit-tests run successfully

2024-09-13 21:46 UTC, LinZhihao-723 requested changes

2024-09-13 21:46 UTC, LinZhihao-723 commented on src/log_surgeon/Lexer.tpp
> +    NFAStateType* end_state = nfa->new_state();
```suggestion
    auto* end_state = nfa->new_state();
```

2024-09-13 21:46 UTC, LinZhihao-723 commented on src/log_surgeon/finite_automata/RegexDFA.hpp
> +    auto add_matching_variable_id(int const& variable_id) -> void {
```suggestion
    auto add_matching_variable_id(int variable_id) -> void {
```
Same, unless we have a reason to enforce using the const reference

2024-09-13 21:46 UTC, LinZhihao-723 commented on src/log_surgeon/finite_automata/RegexDFA.hpp
> +    auto add_matching_variable_id(int const& variable_id) -> void {
This isn't a review question but to help me understand the code. Why are we using `int` for ids here? Do we have negative ids?

2024-09-13 21:46 UTC, LinZhihao-723 commented on src/log_surgeon/finite_automata/RegexDFA.hpp
> +    [[nodiscard]] auto get_first_matching_variable_ids() const -> std::vector<int> const& {
This name is still a little confusing. May be more verbose to say `get_first_state_matching_variable_ids`?

2024-09-13 21:46 UTC, LinZhihao-723 commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +auto RegexDFA<DFAStateType>::new_state(std::set<NFAStateType*> const& nfa_state_set
I might rewrite it this way:
```
    m_states.emplace_back(std::make_unique<DFAStateType>());
    auto* dfa_state = m_states.back().get();
    for (auto const* nfa_state : nfa_state_set) {
        if (nfa_state->is_accepting()) {
            dfa_state->add_matching_variable_id(nfa_state->get_matching_variable_id());
        }
    }
    return dfa_state;
```
1. using `emplace_back` instead of `push_back`
2. using `auto` whenever possible

2024-09-13 21:46 UTC, LinZhihao-723 commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +            schema_types.insert(matching_variable_ids.begin(), matching_variable_ids.end());
```suggestion
            auto const& matching_variable_ids = current_pair_it->get_first_matching_variable_ids();
            schema_types.insert(matching_variable_ids.cbegin(), matching_variable_ids.cend());
```

2024-09-13 21:46 UTC, LinZhihao-723 commented on src/log_surgeon/finite_automata/RegexNFA.hpp
> +    [[nodiscard]] auto get_matching_variable_id() const -> int const& {
```suggestion
    [[nodiscard]] auto get_matching_variable_id() const -> int {
```
Same

2024-09-13 21:46 UTC, LinZhihao-723 commented on src/log_surgeon/finite_automata/RegexNFA.hpp
> +    auto set_matching_variable_id(int const variable_id) -> void {
```suggestion
    auto set_matching_variable_id(int variable_id) -> void {
```

2024-09-13 21:46 UTC, LinZhihao-723 commented on src/log_surgeon/finite_automata/RegexNFA.hpp
> +        int matching_variable_id = old_accepting_state->get_matching_variable_id();
```suggestion
        auto const matching_variable_id = old_accepting_state->get_matching_variable_id();
```

2024-09-13 21:46 UTC, LinZhihao-723 commented on src/log_surgeon/finite_automata/RegexNFA.hpp
> +        int matching_variable_id = src_state->get_matching_variable_id();
```suggestion
        auto const matching_variable_id = src_state->get_matching_variable_id();
```

2024-09-16 11:35 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.hpp
> +    auto add_matching_variable_id(int const& variable_id) -> void {
You're right this should be unsigned, some of the really old code was using int's incorrectly, so it needs to be fixed.

2024-09-16 11:50 UTC, SharafMohamed commented on src/log_surgeon/Lexer.hpp
> +    auto get_rule(uint32_t const& variable_id) -> finite_automata::RegexAST<NFAStateType>*;
Changed to const. Same reason as above.

2024-09-16 11:52 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.hpp
> +    auto add_matching_variable_id(int const& variable_id) -> void {
Changed to const, same reason as above.

2024-09-16 11:55 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.hpp
> +    [[nodiscard]] auto get_first_matching_variable_ids() const -> std::vector<int> const& {
What if we just call it get_matching_variable_ids, and then add a comment that for a RegexDFAStatePair the first state determines the matching variable ids?

2024-09-16 12:01 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexNFA.hpp
> +    auto set_matching_variable_id(int const variable_id) -> void {
Unchanged, same reason as above.

2024-09-16 15:29 UTC, LinZhihao-723 requested changes

2024-09-16 15:29 UTC, LinZhihao-723 commented on src/log_surgeon/Lexer.tpp
> +        rule.add_ast(&nfa);
This is a little weird though as `add_ast` does change the state. Maybe `add_ast` shouldn't be marked as a `const` method?

2024-09-16 15:29 UTC, LinZhihao-723 commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +    DFAStateType* dfa_state = m_states.back().get();
```suggestion
    auto* dfa_state = m_states.back().get();
```

2024-09-16 15:29 UTC, LinZhihao-723 commented on src/log_surgeon/Lexer.tpp
> +        rule.add_ast(&nfa);
Same above

2024-09-16 17:36 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexNFA.hpp
> +        auto matching_variable_id = old_accepting_state->get_matching_variable_id();
changed

2024-09-16 17:37 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexNFA.hpp
> +        auto matching_variable_id = src_state->get_matching_variable_id();
changed

2024-09-16 17:38 UTC, SharafMohamed commented on src/log_surgeon/Lexer.tpp
> +        rule.add_ast(&nfa);
You're right, `add_ast` shouldn't be `const`, I don't know why it even compiles as is.

2024-09-16 17:47 UTC, SharafMohamed commented on src/log_surgeon/Lexer.tpp
> +        rule.add_ast(&nfa);
m_regex->add() doesn't change m_regex, it adds it to the NFA, maybe name needs to be changed?

2024-09-16 17:48 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.tpp
> +    DFAStateType* dfa_state = m_states.back().get();
changed

2024-09-16 21:22 UTC, LinZhihao-723 commented on src/log_surgeon/Lexer.tpp
> +        rule.add_ast(&nfa);
yea that might be better, even though I feel like it should be a method of NFA to add a regex but not the opposite.

2024-09-16 21:44 UTC, LinZhihao-723 commented on src/log_surgeon/Lexer.tpp
> +        rule.add_ast(&nfa);
read the code again. I think I get what you mean and why we need this method. Maybe we can refactor the design a little bit later, but let's delay that to future PRs.

2024-09-16 22:11 UTC, LinZhihao-723 commented on src/log_surgeon/Lexer.tpp
> +        rule.add_ast(&nfa);
reading more. I think what we can do is to make `RegexAst::add` as a const method, and thus make `add_ast` as a const method as well. Also we may want to rename `add_ast` to `add_to_ast` to make it clearer.

2024-09-17 15:46 UTC, SharafMohamed commented on src/log_surgeon/Lexer.tpp
> +        rule.add_ast(&nfa);
Making things const makes sense. Also, I think `add_ast` should be renamed to `add_to_nfa` and `RegexAST::add`, should be renamed to `RegexAST::add_to_nfa`.

2024-09-17 15:56 UTC, SharafMohamed commented on src/log_surgeon/Lexer.tpp
> +        rule.add_ast(&nfa);
Updated in latest commit.

2024-09-17 20:17 UTC, LinZhihao-723 requested changes
After this one should be good

2024-09-17 20:17 UTC, LinZhihao-723 commented on src/log_surgeon/finite_automata/RegexAST.hpp
> +    std::vector<Range> merged_ranges = m_ranges;
```suggestion
    auto merged_ranges = m_ranges;
```

2024-09-18 19:24 UTC, LinZhihao-723 approved these changes
Commit message suggestion:
"Cleanup method and variable naming for `RegexNFA`, `RegexDFA`, and `RegexAst`; Add `LexicalRule` class to replace `Lexer::Rule` struct. (#36)"

2024-09-18 19:42 UTC, merged