Comment cleanup.
y-scope/log-surgeon pull request #37
Opened 2024-09-12 13:19 UTC by SharafMohamed

# Description
- Move comments to more relevant sections.
- Removed "currently" from comments as we don't plan to change it in the future.

2024-09-18 20:46 UTC, LinZhihao-723 requested changes
The rest looks good. Commit message:
"Cleanup inline comments; Add TODO for class renaming. (#37)"

2024-09-18 20:46 UTC, LinZhihao-723 commented on src/log_surgeon/finite_automata/RegexNFA.hpp
> +// TODO: rename `RegexNFA` to `NFA` and `RegexDFA` to `DFA`
Shall we move "`RegexDFA` to `DFA`" to RegexDFA.hpp?

2024-09-19 14:49 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexNFA.hpp
> +// TODO: rename `RegexNFA` to `NFA` and `RegexDFA` to `DFA`
Changed

2024-09-19 14:58 UTC, LinZhihao-723 approved these changes

2024-09-19 14:59 UTC, merged