refactor: Separate DFA functionality into different files.
y-scope/log-surgeon pull request #57
Opened 2024-12-05 16:13 UTC by SharafMohamed

# Description
Separate DFA Functionality into different files. 
- <Will add details here>.

# Validation performed
Current tests still work.

2024-12-06 23:53 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFAState.hpp
> +};
Changed.

2024-12-07 00:18 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFA.hpp
> +) const -> std::set<uint32_t> {
Changed.

2024-12-07 00:18 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFAState.hpp
> +    } else {
Resolved in future PR.

2024-12-10 04:15 UTC, LinZhihao-723 requested changes
The refactoring looks good to me. Let's make an agreement on the macro naming and then we can merge

2024-12-10 04:15 UTC, LinZhihao-723 commented on src/log_surgeon/finite_automata/RegexDFAState.hpp
> +#ifndef LOG_SURGEON_FINITE_AUTOMATA_REGEX_DFA_STATE
Sorry to miss this in previous refactor PRs: I think we should name macros to exactly match the file name, so this header should be `LOG_SURGEON_FINITE_AUTOMATA_REGEXDFASTATE` instead. We can create an issue to keep track of this and fix them all together later

2024-12-11 19:36 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFAState.hpp
> +#ifndef LOG_SURGEON_FINITE_AUTOMATA_REGEX_DFA_STATE
kk sounds good, I'll create the issue.

2024-12-11 19:50 UTC, SharafMohamed commented on src/log_surgeon/finite_automata/RegexDFAState.hpp
> +#ifndef LOG_SURGEON_FINITE_AUTOMATA_REGEX_DFA_STATE
Issue created.

2024-12-11 20:00 UTC, LinZhihao-723 approved these changes
The PR title looks good to me.
The macro naming issue is tracked here: https://github.com/y-scope/log-surgeon/issues/65

2024-12-11 20:01 UTC, merged