Added vars to schema object; fixed 2 timestamp bugs; fixed 1 buffer bug
y-scope/log-surgeon pull request #7
Opened 2023-08-20 10:45 UTC by SharafMohamed

Added vars to schema object
- try_schema_string function added for string schemas since generate_schema_ast is private
- Schema::add_variable() function added

Fixed 2 timestamp bugs
- Bug fixed, where if a newline preceeded the first newlineTimestamp, the first timestamp log would incorrectly contain a newline
- Similar to the above bug, fixed issue where if nontimestamped logs preceeded a timestamped log, the first timestamp log would incorrectly contain a newline

Fixed 1 buffer bug
- Moved all the functionality for increasing capacity into the log_parser class
- Lexer::increase_buffer_capacity() added
- Case where log ends at the buffer halfway/capacity now properly handled

2023-08-21 15:17 UTC, davidlion commented on src/log_surgeon/LogParser.hpp
> +        /// TODO: is the lexer suppose to own the buffer and not the parser?
Move comment to header with `m_input_buffer` and make affirmative.

2023-08-21 15:20 UTC, davidlion commented on src/log_surgeon/LogParser.cpp
> +                // increment by 1 because the '\n' character is not part of the next log message
Drop 3rd `/` and reflow to 80 characters

2023-08-21 15:21 UTC, davidlion commented on src/log_surgeon/LogParser.hpp
> +    /// TODO: move ownership of the buffer to the lexer
```suggestion
    // TODO: move ownership of the buffer to the lexer
```

2023-08-23 09:13 UTC, SharafMohamed commented on src/log_surgeon/LogParser.hpp
> +    /// TODO: move ownership of the buffer to the lexer
Fixed

2023-08-23 09:14 UTC, SharafMohamed commented on src/log_surgeon/LogParser.hpp
> +        /// TODO: is the lexer suppose to own the buffer and not the parser?
Changed

2023-08-23 09:15 UTC, SharafMohamed commented on src/log_surgeon/SchemaParser.cpp
> +            *(buf + i) = schema_string[unparsed_string_pos + i];
Replace *(buf + i) with buf[i]

2023-08-23 09:34 UTC, SharafMohamed commented on src/log_surgeon/SchemaParser.cpp
> +
commiot 5414a9920a7dca2f72625cf14953559d07a7ab9a

2023-08-28 04:23 UTC, kirkrodrigues requested changes

2023-08-28 04:23 UTC, kirkrodrigues commented on src/log_surgeon/Lexer.hpp
> +     * @return ErrorCode::Success
If it only returns `ErrorCode::Success`, we don't need a return value, right? If you do end up keeping the return value, you should specify the type using a trailing return.

2023-08-28 04:23 UTC, kirkrodrigues commented on src/log_surgeon/Lexer.hpp
> +     * @throw It is possible for std::bad_alloc to be thrown in the case
@davidlion, do we need this? I'm not sure how useful it is to the caller and generally any allocation in C++ could throw this right?

2023-08-28 04:42 UTC, davidlion commented on src/log_surgeon/Lexer.hpp
> +     * @throw It is possible for std::bad_alloc to be thrown in the case
I'm indifferent, we can remove it.

2023-08-28 15:02 UTC, SharafMohamed commented on src/log_surgeon/Lexer.hpp
> +     * @throw It is possible for std::bad_alloc to be thrown in the case
I guess we can remove it since we're not the ones throwing it ourselves

2023-08-28 15:09 UTC, SharafMohamed commented on src/log_surgeon/Lexer.hpp
> +     * @return ErrorCode::Success
We can remove it, along with the increase_capacity() error check and return as well.

2023-08-28 15:22 UTC, SharafMohamed commented on src/log_surgeon/Lexer.hpp
> +     * @return ErrorCode::Success
commit 07e0ed83913d0c04be65ca95ec0fed031b33ffb2

2023-08-28 15:22 UTC, SharafMohamed commented on src/log_surgeon/Lexer.hpp
> +     * @throw It is possible for std::bad_alloc to be thrown in the case
commit 07e0ed83913d0c04be65ca95ec0fed031b33ffb2

2023-08-28 20:09 UTC, kirkrodrigues approved these changes

2023-08-29 23:32 UTC, merged