First token in non-timestamped logs now correctly handled; First character of each line in non-timestamped logs now correctly handled
y-scope/log-surgeon pull request #9
Opened 2023-09-18 06:35 UTC by SharafMohamed

# References
Fixes for bugs in https://github.com/y-scope/clp/pull/131 

# Description
- Fixed bug where first token in non-timestamped logs was always stored as static text.
- Fixed bug where first character of every line in non-timestamped logs was always stored as static text.

# Validation performed
Ran version of library in CLP with timestamped, non-timestamped, and mixed logs. Dictionaries, segindexes, and segments all match ground truths. Decompressed logs match originals.

2023-09-20 05:20 UTC, davidlion requested changes

2023-09-20 05:20 UTC, davidlion commented on src/log_surgeon/Constants.hpp
> +    static unsigned char const cCharSOF = 0xFD;
```suggestion
    static unsigned char const cCharStartOfFile = 0xFD;
```

2023-09-20 05:20 UTC, davidlion commented on src/log_surgeon/Lexer.tpp
> +    m_prev_state = m_dfa->get_root()->next(utf8::cCharSOF);
```suggestion
void Lexer<NFAStateType, DFAStateType>::prepend_start_of_file_char(ParserInputBuffer& input_buffer
) {
    m_prev_state = m_dfa->get_root()->next(utf8::cCharStartOfFile);
```

2023-09-20 05:20 UTC, davidlion commented on src/log_surgeon/Lexer.tpp
> +    m_is_delimiter[utf8::cCharSOF] = true;
```suggestion
    m_is_delimiter[utf8::cCharStartOfFile] = true;
```

2023-09-20 05:20 UTC, davidlion commented on src/log_surgeon/Lexer.hpp
> +    auto prepend_SOF(ParserInputBuffer& input_buffer) -> void;
```suggestion
    auto prepend_start_of_file_char(ParserInputBuffer& input_buffer) -> void;
```

2023-09-20 05:20 UTC, davidlion commented on src/log_surgeon/LogParser.cpp
> +    m_lexer.prepend_SOF(m_input_buffer);
```suggestion
    m_lexer.prepend_start_of_file_char(m_input_buffer);
```

2023-09-20 05:20 UTC, davidlion commented on src/log_surgeon/LogParser.cpp
> +                    = make_unique<RegexASTLiteral<RegexNFAByteState>>(utf8::cCharSOF);
```suggestion
                    = make_unique<RegexASTLiteral<RegexNFAByteState>>(utf8::cCharStartOfFile);
```

2023-09-21 16:08 UTC, SharafMohamed commented on src/log_surgeon/LogParser.cpp
> +                    = make_unique<RegexASTLiteral<RegexNFAByteState>>(utf8::cCharSOF);
commit 0e79f78c8d80faa6e6256aeab222d08e98f9243b

2023-09-21 16:08 UTC, SharafMohamed commented on src/log_surgeon/LogParser.cpp
> +    m_lexer.prepend_SOF(m_input_buffer);
commit 0e79f78c8d80faa6e6256aeab222d08e98f9243b

2023-09-21 16:09 UTC, SharafMohamed commented on src/log_surgeon/Lexer.hpp
> +    auto prepend_SOF(ParserInputBuffer& input_buffer) -> void;
commit 0e79f78c8d80faa6e6256aeab222d08e98f9243b

2023-09-21 16:09 UTC, SharafMohamed commented on src/log_surgeon/Lexer.tpp
> +    m_is_delimiter[utf8::cCharSOF] = true;
commit 0e79f78c8d80faa6e6256aeab222d08e98f9243b

2023-09-21 16:09 UTC, SharafMohamed commented on src/log_surgeon/Lexer.tpp
> +    m_prev_state = m_dfa->get_root()->next(utf8::cCharSOF);
commit 0e79f78c8d80faa6e6256aeab222d08e98f9243b

2023-09-21 16:09 UTC, SharafMohamed commented on src/log_surgeon/Constants.hpp
> +    static unsigned char const cCharSOF = 0xFD;
commit 0e79f78c8d80faa6e6256aeab222d08e98f9243b

2023-09-21 17:58 UTC, davidlion requested changes

2023-09-21 17:58 UTC, davidlion commented on src/log_surgeon/Lexer.tpp
> +void Lexer<NFAStateType, DFAStateType>::prepend_start_of_file_char(ParserInputBuffer& input_buffer) {
```suggestion
void Lexer<NFAStateType, DFAStateType>::prepend_start_of_file_char(ParserInputBuffer& input_buffer
) {
```

Over 100 char

2023-09-22 15:02 UTC, davidlion approved these changes

2023-09-22 15:03 UTC, merged